version: '2.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - eci
  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: flowing-retail:1:1
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
    networks:
      - eci

networks:
  eci:
    driver: bridge
    ipam:
      config:
        - subnet: 172.58.0.0/16
